
-- Generated by ORDS REST Data Services 19.4.6.r1421859
-- Schema: WKSP_ANLYD  Date: Sun Jul 04 11:57:32 2021 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'WKSP_ANLYD',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'anlyd',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'anlydcouth.co.uk',
      p_base_path      => '/bricks/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'anlydcouth.co.uk',
      p_pattern        => 'brickdetails/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'anlydcouth.co.uk',
      p_pattern        => 'brickdetails/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => 'To obtain the order details',
      p_source         => 
'select brickid,brcikname
from brickdetails
order by brickid');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'anlydcouth.co.uk',
      p_pattern        => 'orderdetails/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'anlydcouth.co.uk',
      p_pattern        => 'orderdetails/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select orderreference from orderdetails;');

    
        
COMMIT;

END;